2020-12-02 17:33:29,640 univmax_conn.py WARNING : No array id specified. Please set array ID using the "set_array_id(array_id)" function.
2020-12-02 17:33:29,641 dellemc_powermax_gatherfacts.py INFO : Got PyU4V Unisphere instance for common lib method access on VMAX
2020-12-02 17:33:29,641 dellemc_powermax_gatherfacts.py INFO : Getting Array List 
2020-12-02 17:35:29,686 rest_requests.py ERROR : The GET request to URL https://10.126.70.28:8443/univmax/restapi/90/system/symmetrix timed-out, but may have been successful. Please check the array. Exception received: HTTPSConnectionPool(host='10.126.70.28', port=8443): Max retries exceeded with url: /univmax/restapi/90/system/symmetrix (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0ed0b03fd0>, 'Connection to 10.126.70.28 timed out. (connect timeout=120)')).
2020-12-02 17:35:29,687 dellemc_powermax_gatherfacts.py ERROR : ('Get Array List for Unisphere host %s failed with error %s', {'type': 'str', 'required': True}, 'Bad or unexpected response from the storage volume backend API: Error get symmetrix. The status code received is None and the message is None.')
2020-12-03 09:06:08,104 univmax_conn.py WARNING : No array id specified. Please set array ID using the "set_array_id(array_id)" function.
2020-12-03 09:06:08,105 dellemc_powermax_gatherfacts.py INFO : Got PyU4V Unisphere instance for common lib method access on VMAX
2020-12-03 09:06:08,105 dellemc_powermax_gatherfacts.py INFO : Getting Array List 
2020-12-03 09:08:08,174 rest_requests.py ERROR : The GET request to URL https://10.126.70.28:8443/univmax/restapi/90/system/symmetrix timed-out, but may have been successful. Please check the array. Exception received: HTTPSConnectionPool(host='10.126.70.28', port=8443): Max retries exceeded with url: /univmax/restapi/90/system/symmetrix (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7dc5e84f60>, 'Connection to 10.126.70.28 timed out. (connect timeout=120)')).
2020-12-03 09:08:08,174 dellemc_powermax_gatherfacts.py ERROR : ('Get Array List for Unisphere host %s failed with error %s', {'type': 'str', 'required': True}, 'Bad or unexpected response from the storage volume backend API: Error get symmetrix. The status code received is None and the message is None.')
2020-12-03 09:15:55,934 univmax_conn.py WARNING : No array id specified. Please set array ID using the "set_array_id(array_id)" function.
2020-12-03 09:15:55,934 dellemc_powermax_gatherfacts.py INFO : Got PyU4V Unisphere instance for common lib method access on VMAX
2020-12-03 09:15:55,934 dellemc_powermax_gatherfacts.py INFO : Getting Array List 
2020-12-03 09:17:55,939 rest_requests.py ERROR : The GET request to URL https://10.126.70.28:8443/univmax/restapi/90/system/symmetrix timed-out, but may have been successful. Please check the array. Exception received: HTTPSConnectionPool(host='10.126.70.28', port=8443): Max retries exceeded with url: /univmax/restapi/90/system/symmetrix (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f6beaecffd0>, 'Connection to 10.126.70.28 timed out. (connect timeout=120)')).
2020-12-03 09:17:55,939 dellemc_powermax_gatherfacts.py ERROR : ('Get Array List for Unisphere host %s failed with error %s', {'type': 'str', 'required': True}, 'Bad or unexpected response from the storage volume backend API: Error get symmetrix. The status code received is None and the message is None.')
